Add command line interface to predict and plot a single peptide spectrum
compomics/ms2pip_c pull request #136
Opened 2021-03-22 13:14 UTC by RalfG

With `ms2pip-single-prediction` a single peptide spectrum can be predicted with MS²PIP and plotted with [spectrum_utils](https://spectrum-utils.readthedocs.io/). For instance:

```sh
ms2pip-single-prediction "PGAQANPYSR" "-" 3 --model TMT
```

will write the following image to a file:

![PGAQANPYSR-3-TMT](https://user-images.githubusercontent.com/26458971/111995021-c1184000-8b18-11eb-8d34-97c647821e97.png)

2021-03-23 09:02 UTC, RalfG commented
Tests fail because rdkit cannot be imported (cannot be installed with pip). See bittremieux/spectrum_utils#14

2021-04-01 12:41 UTC, RalfG commented
RDKit issue has been fixed.

2021-04-02 14:24 UTC, paretje requested changes

2021-04-02 14:24 UTC, paretje commented on ms2pip/single_prediction.py
> +    return [item for sublist in nested_list for item in sublist]
Would `itertools.chain.from_iterable` be an alternative?

2021-09-08 08:30 UTC, paretje requested changes

2021-09-08 08:30 UTC, paretje commented on ms2pip/single_prediction.py
> +    return [item for sublist in nested_list for item in sublist]
```suggestion
```

2021-09-08 10:05 UTC, paretje approved these changes

2021-09-08 10:05 UTC, merged